name: Gitflow release
description: Release following Gitflow branching model
author: Gerard Vico
inputs:
  command:
    description: Supported commands are [start|finish|start_finish]
    required: true
  tag:
    description: A Git tag name.
    required: true
  main_branch:
    description: Branch storing the official release history
    required: false
    default: master
  develop_branch:
    description: Branch serving as an integration branch for features
    required: false
    default: develop
  skip_empty_releases:
    description: Skip integrate releases with 0 commits ahead your main branch
    required: false
    default: "true"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
    - ${{ inputs.tag }}
    - ${{ inputs.main_branch }}
    - ${{ inputs.develop_branch }}
    - ${{ inputs.skip_empty_releases }}
branding:
  icon: 'award'
  color: 'green'